const fs = require('fs');

const lines = [];
lines.push('/**');
lines.push(' * VaultBank API Service');
lines.push(' * Handles all communication with the backend server');
lines.push(' */');
lines.push('');
lines.push("const API_BASE = 'https://vaultbank-md20.onrender.com';");
lines.push('');
lines.push('interface AuthResponse {');
lines.push('  success: boolean;');
lines.push('  token?: string;');
lines.push('  user?: {');
lines.push('    id: string;');
lines.push('    email: string;');
lines.push('    full_name?: string;');
lines.push('    fullName?: string;');
lines.push('    role?: string;');
lines.push('  };');
lines.push('  account?: {');
lines.push('    id: string;');
lines.push('    accountNumber: string;');
lines.push('    accountType: string;');
lines.push('    balance: number;');
lines.push('    availableBalance?: number;');
lines.push('    currency: string;');
lines.push('    status?: string;');
lines.push('  };');
lines.push('  message?: string;');
lines.push('}');
lines.push('');
lines.push('interface ApiResponse<T = any> {');
lines.push('  success: boolean;');
lines.push('  data?: T;');
lines.push('  message?: string;');
lines.push('  [key: string]: any;');
lines.push('}');
lines.push('');
lines.push('class ApiError extends Error {');
lines.push('  status: number;');
lines.push('  constructor(message: string, status: number) {');
lines.push('    super(message);');
lines.push('    this.status = status;');
lines.push("    this.name = 'ApiError';");
lines.push('  }');
lines.push('}');
lines.push('');
lines.push('const MAX_RETRIES = 2;');
lines.push('const RETRY_DELAY_MS = 1500;');
lines.push('');
lines.push('function delay(ms: number): Promise<void> {');
lines.push('  return new Promise((resolve) => setTimeout(resolve, ms));');
lines.push('}');
lines.push('');
lines.push('function buildUrl(endpoint: string): string {');
lines.push("  const base = API_BASE.replace(/\\/+$/, '');");
lines.push("  const path = endpoint.replace(/^\\/+/, '');");
lines.push('  return `${base}/${path}`;');
lines.push('}');
lines.push('');
lines.push('async function request<T = any>(endpoint: string, options: RequestInit = {}): Promise<T> {');
lines.push("  const token = localStorage.getItem('vaultbank_token');");
lines.push('  const headers: Record<string, string> = {');
lines.push("    'Content-Type': 'application/json',");
lines.push('    ...((options.headers as Record<string, string>) || {}),');
lines.push('  };');
lines.push('  if (token) {');
lines.push('    headers[\'Authorization\'] = `Bearer ${token}`;');
lines.push('  }');
lines.push('  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {');
lines.push('    try {');
lines.push('      const response = await fetch(buildUrl(endpoint), { ...options, headers });');
lines.push('      const data = await response.json();');
lines.push('      if (!response.ok) {');
lines.push("        throw new ApiError(data.message || 'Request failed', response.status);");
lines.push('      }');
lines.push('      return data as T;');
lines.push('    } catch (error) {');
lines.push('      if (error instanceof ApiError) throw error;');
lines.push('      console.warn(`[API] Network error for ${endpoint} (attempt ${attempt + 1}/${MAX_RETRIES + 1}):`, error);');
lines.push('      if (attempt < MAX_RETRIES) {');
lines.push('        await delay(RETRY_DELAY_MS);');
lines.push('      }');
lines.push('    }');
lines.push('  }');
lines.push("  throw new ApiError('Cannot reach the server. Please check your internet connection and try again.', 0);");
lines.push('}');
lines.push('');
lines.push('export const api = {');
lines.push('  async login(email: string, password: string): Promise<AuthResponse> {');
lines.push('    try {');
lines.push("      const result = await request<AuthResponse>('login', {");
lines.push("        method: 'POST',");
lines.push('        body: JSON.stringify({ email, password }),');
lines.push('      });');
lines.push('      if (result.token) {');
lines.push("        localStorage.setItem('vaultbank_token', result.token);");
lines.push("        if (result.user) localStorage.setItem('vaultbank_user', JSON.stringify(result.user));");
lines.push("        if (result.account) localStorage.setItem('vaultbank_account', JSON.stringify(result.account));");
lines.push('      }');
lines.push('      return result;');
lines.push('    } catch (error) {');
lines.push('      throw error;');
lines.push('    }');
lines.push('  },');
lines.push('');
lines.push('  async signup(email: string, password: string, fullName?: string): Promise<AuthResponse> {');
lines.push('    try {');
lines.push("      const result = await request<AuthResponse>('signup', {");
lines.push("        method: 'POST',");
lines.push('        body: JSON.stringify({ email, password, fullName }),');
lines.push('      });');
lines.push('      if (result.token) {');
lines.push("        localStorage.setItem('vaultbank_token', result.token);");
lines.push("        if (result.user) localStorage.setItem('vaultbank_user', JSON.stringify(result.user));");
lines.push("        if (result.account) localStorage.setItem('vaultbank_account', JSON.stringify(result.account));");
lines.push('      }');
lines.push('      return result;');
lines.push('    } catch (error) {');
lines.push('      throw error;');
lines.push('    }');
lines.push('  },');
lines.push('');
lines.push('  async adminLogin(email: string, password: string): Promise<AuthResponse> {');
lines.push('    try {');
lines.push("      const result = await request<AuthResponse>('api/auth/login', {");
lines.push("        method: 'POST',");
lines.push('        body: JSON.stringify({ email, password }),');
lines.push('      });');
lines.push('      if (result.token) {');
lines.push("        localStorage.setItem('vaultbank_token', result.token);");
lines.push("        if (result.user) localStorage.setItem('vaultbank_user', JSON.stringify(result.user));");
lines.push("        if (result.account) localStorage.setItem('vaultbank_account', JSON.stringify(result.account));");
lines.push('      }');
lines.push('      return result;');
lines.push('    } catch (error) {');
lines.push('      throw error;');
lines.push('    }');
lines.push('  },');
lines.push('');
lines.push('  logout(): void {');
lines.push("    localStorage.removeItem('vaultbank_token');");
lines.push("    localStorage.removeItem('vaultbank_user');");
lines.push("    localStorage.removeItem('vaultbank_account');");
lines.push('  },');
lines.push('');
lines.push('  getToken(): string | null {');
lines.push("    return localStorage.getItem('vaultbank_token');");
lines.push('  },');
lines.push('');
lines.push('  getUser(): any | null {');
lines.push("    const user = localStorage.getItem('vaultbank_user');");
lines.push('    return user ? JSON.parse(user) : null;');
lines.push('  },');
lines.push('');
lines.push('  getAccount(): any | null {');
lines.push("    const account = localStorage.getItem('vaultbank_account');");
lines.push('    return account ? JSON.parse(account) : null;');
lines.push('  },');
lines.push('');
lines.push('  isAuthenticated(): boolean {');
lines.push("    return !!localStorage.getItem('vaultbank_token');");
lines.push('  },');
lines.push('');
lines.push('  async getProfile(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/auth/me');");
lines.push('  },');
lines.push('');
lines.push('  async getAccounts(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/accounts');");
lines.push('  },');
lines.push('');
lines.push('  async getAccount(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/account');");
lines.push('  },');
lines.push('');
lines.push('  async getAccountBalance(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/account/balance');");
lines.push('  },');
lines.push('');
lines.push('  async getAccountTransactions(limit = 50): Promise<ApiResponse> {');
lines.push('    return request<ApiResponse>(`api/account/transactions?limit=${limit}`);');
lines.push('  },');
lines.push('');
lines.push('  async getTransfers(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/transfers');");
lines.push('  },');
lines.push('');
lines.push('  async createTransfer(data: { toAccountId?: string; amount: number; currency?: string; description?: string }): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/transfers', {");
lines.push("      method: 'POST',");
lines.push('      body: JSON.stringify(data),');
lines.push('    });');
lines.push('  },');
lines.push('');
lines.push('  async getTransferHistory(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/transfers/history');");
lines.push('  },');
lines.push('');
lines.push('  async getRewards(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/rewards/me');");
lines.push('  },');
lines.push('');
lines.push('  async getLeaderboard(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/rewards/leaderboard');");
lines.push('  },');
lines.push('');
lines.push('  async redeemReward(points: number): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/rewards/redeem', {");
lines.push("      method: 'POST',");
lines.push('      body: JSON.stringify({ points }),');
lines.push('    });');
lines.push('  },');
lines.push('');
lines.push('  async getAlerts(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/alerts');");
lines.push('  },');
lines.push('');
lines.push('  async getUnreadCount(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/alerts/unread-count');");
lines.push('  },');
lines.push('');
lines.push('  async markAlertRead(id: string): Promise<ApiResponse> {');
lines.push('    return request<ApiResponse>(`api/alerts/${id}/read`, { method: \'PUT\' });');
lines.push('  },');
lines.push('');
lines.push('  async markAllAlertsRead(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/alerts/read-all', { method: 'PUT' });");
lines.push('  },');
lines.push('');
lines.push('  async getInvestments(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/investments/me');");
lines.push('  },');
lines.push('');
lines.push('  async addInvestment(data: { type: string; amount: number; description?: string }): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/investments/add', {");
lines.push("      method: 'POST',");
lines.push('      body: JSON.stringify(data),');
lines.push('    });');
lines.push('  },');
lines.push('');
lines.push('  async getPaymentMethods(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/payments/methods');");
lines.push('  },');
lines.push('');
lines.push('  async initiatePayment(data: { method: string; amount: number; currency?: string; to?: string; metadata?: any }): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/payments/transfer', {");
lines.push("      method: 'POST',");
lines.push('      body: JSON.stringify(data),');
lines.push('    });');
lines.push('  },');
lines.push('');
lines.push('  async getPaymentHistory(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/payments/history');");
lines.push('  },');
lines.push('');
lines.push('  async getWalletBalance(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/payments/wallet/balance');");
lines.push('  },');
lines.push('');
lines.push('  async getAdminStats(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/admin/stats');");
lines.push('  },');
lines.push('');
lines.push('  async getAdminUsers(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/admin/users');");
lines.push('  },');
lines.push('');
lines.push('  async getAdminTransactions(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('api/admin/transactions');");
lines.push('  },');
lines.push('');
lines.push('  async healthCheck(): Promise<ApiResponse> {');
lines.push("    return request<ApiResponse>('health');");
lines.push('  },');
lines.push('};');
lines.push('');
lines.push('export { ApiError };');
lines.push('export type { AuthResponse, ApiResponse };');
lines.push('');

fs.writeFileSync('client/src/api.ts', lines.join('\n'), 'utf8');
console.log('api.ts written successfully with ' + lines.length + ' lines');